import { User, Project, Task, ProjectTemplate } from './types';

// Mock Users
export const mockUsers: User[] = [
    { id: 'user-1', name: 'Alex Chen', email: 'alex@aha.com', role: 'admin', avatar: '' },
    { id: 'user-2', name: 'Sarah Kim', email: 'sarah@aha.com', role: 'manager', avatar: '' },
    { id: 'user-3', name: 'Mike Johnson', email: 'mike@aha.com', role: 'member', avatar: '' },
    { id: 'user-4', name: 'Emily Davis', email: 'emily@aha.com', role: 'member', avatar: '' },
];

// Mock Projects
export const mockProjects: Project[] = [
    {
        id: 'proj-1',
        name: 'Website Redesign',
        description: 'Complete overhaul of the company website with modern design',
        status: 'active',
        deadline: '2026-02-28',
        createdAt: '2026-01-10',
        color: '#6366f1',
    },
    {
        id: 'proj-2',
        name: 'Mobile App Launch',
        description: 'Launch the new mobile application for iOS and Android',
        status: 'active',
        deadline: '2026-03-15',
        createdAt: '2026-01-05',
        color: '#8b5cf6',
    },
    {
        id: 'proj-3',
        name: 'Q1 Marketing Campaign',
        description: 'Execute Q1 marketing initiatives across all channels',
        status: 'active',
        deadline: '2026-03-31',
        createdAt: '2026-01-01',
        color: '#ec4899',
    },
];

// Mock Tasks
export const mockTasks: Task[] = [
    // Website Redesign Tasks
    {
        id: 'task-1',
        title: 'Design new homepage mockup',
        description: 'Create wireframes and high-fidelity mockups for the new homepage',
        assigneeId: 'user-2',
        priority: 'high',
        status: 'done',
        dueDate: '2026-01-18',
        isRecurring: false,
        recurrence: 'none',
        projectId: 'proj-1',
        createdAt: '2026-01-10',
        completedAt: '2026-01-17',
    },
    {
        id: 'task-2',
        title: 'Implement responsive navigation',
        description: 'Build the new navigation component with mobile support',
        assigneeId: 'user-1',
        priority: 'high',
        status: 'in-progress',
        dueDate: '2026-01-22',
        isRecurring: false,
        recurrence: 'none',
        projectId: 'proj-1',
        createdAt: '2026-01-11',
        completedAt: null,
    },
    {
        id: 'task-3',
        title: 'Set up CI/CD pipeline',
        description: 'Configure automated deployment for the new website',
        assigneeId: 'user-3',
        priority: 'medium',
        status: 'todo',
        dueDate: '2026-01-25',
        isRecurring: false,
        recurrence: 'none',
        projectId: 'proj-1',
        createdAt: '2026-01-12',
        completedAt: null,
    },
    {
        id: 'task-4',
        title: 'Content migration',
        description: 'Migrate existing content to the new CMS structure',
        assigneeId: 'user-4',
        priority: 'medium',
        status: 'review',
        dueDate: '2026-01-23',
        isRecurring: false,
        recurrence: 'none',
        projectId: 'proj-1',
        createdAt: '2026-01-13',
        completedAt: null,
    },
    // Mobile App Tasks
    {
        id: 'task-5',
        title: 'Fix authentication bug',
        description: 'Resolve the login issue on Android devices',
        assigneeId: 'user-1',
        priority: 'high',
        status: 'done',
        dueDate: '2026-01-15',
        isRecurring: false,
        recurrence: 'none',
        projectId: 'proj-2',
        createdAt: '2026-01-08',
        completedAt: '2026-01-14',
    },
    {
        id: 'task-6',
        title: 'App Store submission',
        description: 'Prepare and submit the app to Apple App Store',
        assigneeId: 'user-2',
        priority: 'high',
        status: 'todo',
        dueDate: '2026-02-01',
        isRecurring: false,
        recurrence: 'none',
        projectId: 'proj-2',
        createdAt: '2026-01-10',
        completedAt: null,
    },
    {
        id: 'task-7',
        title: 'Push notification testing',
        description: 'Test push notifications across all device types',
        assigneeId: 'user-3',
        priority: 'medium',
        status: 'in-progress',
        dueDate: '2026-01-28',
        isRecurring: false,
        recurrence: 'none',
        projectId: 'proj-2',
        createdAt: '2026-01-12',
        completedAt: null,
    },
    // Marketing Tasks
    {
        id: 'task-8',
        title: 'Weekly social media posts',
        description: 'Create and schedule social media content for the week',
        assigneeId: 'user-4',
        priority: 'medium',
        status: 'done',
        dueDate: '2026-01-19',
        isRecurring: true,
        recurrence: 'weekly',
        projectId: 'proj-3',
        createdAt: '2026-01-05',
        completedAt: '2026-01-18',
    },
    {
        id: 'task-9',
        title: 'Monthly newsletter',
        description: 'Draft and send the monthly newsletter to subscribers',
        assigneeId: 'user-2',
        priority: 'high',
        status: 'todo',
        dueDate: '2026-01-31',
        isRecurring: true,
        recurrence: 'monthly',
        projectId: 'proj-3',
        createdAt: '2026-01-02',
        completedAt: null,
    },
    {
        id: 'task-10',
        title: 'Daily analytics review',
        description: 'Review and report on daily marketing metrics',
        assigneeId: 'user-3',
        priority: 'low',
        status: 'in-progress',
        dueDate: '2026-01-20',
        isRecurring: true,
        recurrence: 'daily',
        projectId: 'proj-3',
        createdAt: '2026-01-01',
        completedAt: null,
    },
];

// Project Templates
export const mockTemplates: ProjectTemplate[] = [
    {
        id: 'template-1',
        name: 'Sprint Planning',
        description: 'Standard 2-week sprint template with all necessary ceremonies',
        tasks: [
            { title: 'Sprint Planning Meeting', description: 'Define sprint goals and backlog', assigneeId: null, priority: 'high', status: 'todo', dueDate: null, isRecurring: false, recurrence: 'none' },
            { title: 'Daily Standup', description: 'Daily team sync', assigneeId: null, priority: 'medium', status: 'todo', dueDate: null, isRecurring: true, recurrence: 'daily' },
            { title: 'Backlog Grooming', description: 'Review and prioritize backlog items', assigneeId: null, priority: 'medium', status: 'todo', dueDate: null, isRecurring: false, recurrence: 'none' },
            { title: 'Sprint Review', description: 'Demo completed work to stakeholders', assigneeId: null, priority: 'high', status: 'todo', dueDate: null, isRecurring: false, recurrence: 'none' },
            { title: 'Sprint Retrospective', description: 'Team reflection and improvement planning', assigneeId: null, priority: 'medium', status: 'todo', dueDate: null, isRecurring: false, recurrence: 'none' },
        ],
    },
    {
        id: 'template-2',
        name: 'Product Launch',
        description: 'Comprehensive checklist for launching a new product',
        tasks: [
            { title: 'Finalize product features', description: 'Lock down feature set for launch', assigneeId: null, priority: 'high', status: 'todo', dueDate: null, isRecurring: false, recurrence: 'none' },
            { title: 'QA Testing', description: 'Complete quality assurance testing', assigneeId: null, priority: 'high', status: 'todo', dueDate: null, isRecurring: false, recurrence: 'none' },
            { title: 'Marketing materials', description: 'Prepare launch marketing content', assigneeId: null, priority: 'medium', status: 'todo', dueDate: null, isRecurring: false, recurrence: 'none' },
            { title: 'Press release', description: 'Draft and distribute press release', assigneeId: null, priority: 'medium', status: 'todo', dueDate: null, isRecurring: false, recurrence: 'none' },
            { title: 'Customer support training', description: 'Train support team on new product', assigneeId: null, priority: 'medium', status: 'todo', dueDate: null, isRecurring: false, recurrence: 'none' },
            { title: 'Launch day monitoring', description: 'Monitor systems and feedback on launch day', assigneeId: null, priority: 'high', status: 'todo', dueDate: null, isRecurring: false, recurrence: 'none' },
        ],
    },
    {
        id: 'template-3',
        name: 'Weekly Operations',
        description: 'Recurring weekly operational tasks',
        tasks: [
            { title: 'Team standup', description: 'Weekly all-hands meeting', assigneeId: null, priority: 'high', status: 'todo', dueDate: null, isRecurring: true, recurrence: 'weekly' },
            { title: 'Review metrics', description: 'Analyze weekly performance metrics', assigneeId: null, priority: 'medium', status: 'todo', dueDate: null, isRecurring: true, recurrence: 'weekly' },
            { title: 'Client check-in', description: 'Weekly client status update', assigneeId: null, priority: 'high', status: 'todo', dueDate: null, isRecurring: true, recurrence: 'weekly' },
            { title: 'Update documentation', description: 'Keep project docs up to date', assigneeId: null, priority: 'low', status: 'todo', dueDate: null, isRecurring: true, recurrence: 'weekly' },
        ],
    },
];
